### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'backup/metayolo_novel0_neg1'

### ISSUE THREAD

**Issue by myh12138** [bingykang/Fewshot_Detection#52]
Anyone have a backup file in your program?
`python train_meta.py cfg/metayolo.data cfg/darknet_dynamic.cfg cfg/reweighting_net.cfg darknet19_448.conv.23
/home/myh/Documents/program/few-shot-learning/Fewshot_Detection-master/data/coco.names
save_interval 10
['bird', 'bus', 'cow', 'motorbike', 'sofa']
base_ids [0, 1, 3, 4, 6, 7, 8, 10, 11, 12, 14, 15, 16, 18, 19]
logging to backup/metayolo_novel0_neg1
Traceback (most recent call last):
  File "train_meta.py", line 79, in <module>
    os.mkdir(backupdir)
FileNotFoundError: [Errno 2] No such file or directory: 'backup/metayolo_novel0_neg1'
`

**Comment by LDZ233** [comment]
You should create this file manually

**Comment by myh12138** [comment]
> You should create this file manually

Does it need anything in it？Or just a empty file?Thinks.

**Comment by yanxiaod123** [comment]
I met the same problem. How did you solve it? @myh12138

**Comment by VinhLoiIT** [comment]
Just create an empty folder named "backup" in your PROJ_ROOT

**Comment by zhanghao5** [comment]
use this python method os.makedirs()

**Comment by myh12138** [comment]
> I met the same problem. How did you solve it? @myh12138

Yes,as they said to make an empty folder.But the results made by me is 0000000,I don not why.

**Comment by Zyt-wenwne** [comment]
> 
> 
> You should create this file manually

 Hi,​  when I run the code , a error happened,
**
Traceback (most recent call last):
File "train_meta.py", line 352, in
train(epoch)
File "train_meta.py", line 197, in train
loss,recall_rate,conf_proposal,loss_bbox,loss_conf,loss_cls = region_loss(output, target)
File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in call
result = self.forward(*input, **kwargs)
File "/home/plc319/桌面/Few-shot-Object-Detection-via-Feature-Reweighting-main/models/layers/region_loss.py", line 296, in forward
cls = cls.view(bs, cs, nA * nC * nH * nW).transpose(1, 2).contiguous().view(bs * nA * nC * nH * nW, cs)
RuntimeError: shape '[32, 15, 845]' is invalid for input of size 540800
**
can you tell me how to solve the problem, I know is the tensor's error , BUT how to solve it without influence to the model
