### ISSUE TITLE
loss get very big?

### ISSUE THREAD

**Issue by jinweiLiu** [bingykang/Fewshot_Detection#60]
After a period of training, the loss becomes great，even nan

**Comment by mora-st** [comment]
You can decrease the lr, or use burn_in.
I have implemented burn_in, and it helped
train_meta.py:
```
def adjust_learning_rate(optimizer, batch):
    """Sets the learning rate to the initial LR decayed by 10 every 30 epochs"""
    lr = learning_rate

    if batch <= burn_in:
        lr = lr * (batch / burn_in) ** 4

    for i in range(len(steps)):
        scale = scales[i] if i < len(scales) else 1
        if batch >= steps[i]:
            lr = lr * scale
            if batch == steps[i]:
                break
        else:
            break
    for param_group in optimizer.param_groups:
        param_group['lr'] = lr/batch_size
    return lr

```

**Comment by jinweiLiu** [comment]
Thanks a lot, I found the issue

**Comment by jinweiLiu** [comment]
Another problem occurred. When  I eval the base model, I got an error of out of memory even I have set batch_size = 1. Do you have the same issue.

**Comment by Zyt-wenwne** [comment]
> 
> 
> You can decrease the lr, or use burn_in.
> I have implemented burn_in, and it helped
> train_meta.py:
> 
> ```
> def adjust_learning_rate(optimizer, batch):
>     """Sets the learning rate to the initial LR decayed by 10 every 30 epochs"""
>     lr = learning_rate
> 
>     if batch <= burn_in:
>         lr = lr * (batch / burn_in) ** 4
> 
>     for i in range(len(steps)):
>         scale = scales[i] if i < len(scales) else 1
>         if batch >= steps[i]:
>             lr = lr * scale
>             if batch == steps[i]:
>                 break
>         else:
>             break
>     for param_group in optimizer.param_groups:
>         param_group['lr'] = lr/batch_size
>     return lr
> ```

 Hi,​ when I run the code , a error happened,
**
Traceback (most recent call last):
File "train_meta.py", line 352, in
train(epoch)
File "train_meta.py", line 197, in train
loss,recall_rate,conf_proposal,loss_bbox,loss_conf,loss_cls = region_loss(output, target)
File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in call
result = self.forward(*input, **kwargs)
File "/home/plc319/桌面/Few-shot-Object-Detection-via-Feature-Reweighting-main/models/layers/region_loss.py", line 296, in forward
cls = cls.view(bs, cs, nA * nC * nH * nW).transpose(1, 2).contiguous().view(bs * nA * nC * nH * nW, cs)
RuntimeError: shape '[32, 15, 845]' is invalid for input of size 540800
**

can you tell me how to solve the problem, I know is the tensor's error , BUT how to solve it without influence to the model

**Comment by mora-st** [comment]
in region_loss.py, change this lines helped me: (add axis=1)

else:
            flags = [0 if f == 0 and random() > ratio else 1 for f in flags]
            inds = np.argwhere(flags).squeeze(*axis=1*)
            pred_boxes, target = pred_boxes[inds], target[inds]
