### ISSUE TITLE
RuntimeError: The size of tensor a (3) must match the size of tensor b (864) at non-singleton dimension 3

### ISSUE THREAD

**Issue by edlawson** [bingykang/Fewshot_Detection#76]
I'm having some issues running train_meta.  Specifically, I get the above error.  All messages are:

~/Fewshot_Detection$ python train_meta.py cfg/metayolo.data cfg/darknet_dynamic.cfg cfg/reweighting_net.cfg darknet19_448.conv.23
/home/elawson/Fewshot_Detection/data/coco.names
save_interval 10
['bird', 'bus', 'cow', 'motorbike', 'sofa']
base_ids [0, 1, 3, 4, 6, 7, 8, 10, 11, 12, 14, 15, 16, 18, 19]
logging to backup/metayolo_novel0_neg1
class_scale 1
Traceback (most recent call last):
  File "train_meta.py", line 87, in <module>
    model.load_weights(weightfile)
  File "/home/elawson/Fewshot_Detection/darknet_meta.py", line 378, in load_weights
    start = load_conv_bn(buf, start, model[0], model[1])
  File "/home/elawson/Fewshot_Detection/cfg.py", line 455, in load_conv_bn
    conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w 
RuntimeError: The size of tensor a (3) must match the size of tensor b (864) at non-singleton dimension 3

Suggestions?

**Comment by WqxLoveCoding** [comment]
hello, have you fixed it yet? I met the same problem

**Comment by fish-kong** [comment]
hello, have you fixed it yet? I met the same problem

**Comment by 2563895797** [comment]
hello, have you fixed it yet? I met the same problem

**Comment by xyqqqfs** [comment]
hello, have you fixed it yet? I met the same problem

**Comment by xyqqqfs** [comment]
https://github.com/bingykang/Fewshot_Detection/issues/7#issuecomment-753658247
I followed this method and it worked, you can try it

**Comment by STSTERANDMOMO** [comment]
TypeError: only integer tensors of a single element can be converted to an index
Have you met this problem?
